from django.urls import path

from .views import (
    admin_academic_catalogs_view,
    admin_academic_enrollment_selected_view,
    admin_academic_enrollment_students_view,
    admin_attendance_save_view,
    admin_attendance_view,
    admin_bulk_enrollment_template_view,
    admin_bulk_enrollment_view,
    admin_carrera_status_view,
    admin_certificate_download_view,
    admin_certificate_generate_view,
    admin_certificate_students_view,
    admin_certificate_template_preview_view,
    admin_certificate_template_save_view,
    admin_certificate_template_view,
    admin_course_cut_close_view,
    admin_course_cut_create_view,
    admin_course_cut_students_sync_view,
    admin_course_cut_students_view,
    admin_course_cut_schedule_save_view,
    admin_course_cut_schedule_view,
    admin_course_cut_teams_sync_view,
    admin_course_cuts_view,
    admin_enrolled_students_view,
    admin_grade_transfer_save_view,
    admin_grade_transfer_view,
    admin_payment_cancel_view,
    admin_payment_info_view,
    admin_payment_operations_generate_view,
    admin_payment_operations_links_view,
    admin_payment_operations_view,
    admin_registered_payments_view,
    admin_payment_register_view,
    admin_payments_reconcile_view,
    admin_payment_discount_view,
    admin_payment_receipt_generate_view,
    admin_pensum_entry_view,
    admin_pensum_status_view,
    admin_teacher_candidates_view,
    admin_teacher_entry_view,
    admin_teacher_enrollment_view,
    certificate_verify_view,
    health_view,
    inscription_certificate_view,
    inscription_catalogs_view,
    inscription_generate_matricula_view,
    inscription_payment_link_view,
    login_view,
    microsoft365_create_user_view,
    microsoft365_student_license_view,
    notifications_read_view,
    notifications_view,
    student_certificate_download_view,
    student_certificate_preview_view,
    student_certificate_send_view,
    student_grades_dashboard_view,
    student_schedule_dashboard_view,
    student_lookup_view,
    teacher_attendance_dashboard_view,
    teacher_attendance_roster_view,
    teacher_attendance_save_view,
    teacher_course_dashboard_view,
    teacher_grades_dashboard_view,
    teacher_schedule_dashboard_view,
    teacher_schedule_save_view,
)


urlpatterns = [
    path('health/', health_view, name='auth-health'),
    path('login/', login_view, name='auth-login'),
    path('notifications/', notifications_view, name='dashboard-notifications'),
    path('notifications/read/', notifications_read_view, name='dashboard-notifications-read'),
    path('inscription/lookup/', student_lookup_view, name='student-lookup'),
    path('inscription/catalogs/', inscription_catalogs_view, name='inscription-catalogs'),
    path('inscription/matricula/', inscription_generate_matricula_view, name='inscription-matricula'),
    path('inscription/payment-link/', inscription_payment_link_view, name='inscription-payment-link'),
    path('inscription/certificate/', inscription_certificate_view, name='inscription-certificate'),
    path('certificates/verify/', certificate_verify_view, name='certificate-verify'),
    path('microsoft365/users/', microsoft365_create_user_view, name='microsoft365-create-user'),
    path('microsoft365/licenses/student/', microsoft365_student_license_view, name='microsoft365-student-license'),
    path('teacher/courses/', teacher_course_dashboard_view, name='teacher-course-dashboard'),
    path('teacher/attendance/', teacher_attendance_dashboard_view, name='teacher-attendance-dashboard'),
    path('teacher/attendance/roster/', teacher_attendance_roster_view, name='teacher-attendance-roster'),
    path('teacher/attendance/save/', teacher_attendance_save_view, name='teacher-attendance-save'),
    path('teacher/schedule/', teacher_schedule_dashboard_view, name='teacher-schedule-dashboard'),
    path('teacher/schedule/save/', teacher_schedule_save_view, name='teacher-schedule-save'),
    path('teacher/grades/', teacher_grades_dashboard_view, name='teacher-grades-dashboard'),
    path('student/schedule/', student_schedule_dashboard_view, name='student-schedule-dashboard'),
    path('student/grades/', student_grades_dashboard_view, name='student-grades-dashboard'),
    path('student/certificate/preview/', student_certificate_preview_view, name='student-certificate-preview'),
    path('student/certificate/download/', student_certificate_download_view, name='student-certificate-download'),
    path('student/certificate/send/', student_certificate_send_view, name='student-certificate-send'),
    path('admin/certificate-template/', admin_certificate_template_view, name='admin-certificate-template'),
    path('admin/certificate-template/save/', admin_certificate_template_save_view, name='admin-certificate-template-save'),
    path('admin/certificate-template/preview/', admin_certificate_template_preview_view, name='admin-certificate-template-preview'),
    path('admin/certificates/students/', admin_certificate_students_view, name='admin-certificate-students'),
    path('admin/certificates/generate/', admin_certificate_generate_view, name='admin-certificate-generate'),
    path('admin/certificates/download/', admin_certificate_download_view, name='admin-certificate-download'),
    path('admin/academic-catalogs/', admin_academic_catalogs_view, name='admin-academic-catalogs'),
    path('admin/academic-enrollment/students/', admin_academic_enrollment_students_view, name='admin-academic-enrollment-students'),
    path('admin/academic-enrollment/selected/', admin_academic_enrollment_selected_view, name='admin-academic-enrollment-selected'),
    path('admin/teachers/', admin_teacher_candidates_view, name='admin-teacher-candidates'),
    path('admin/teacher-entry/', admin_teacher_entry_view, name='admin-teacher-entry'),
    path('admin/teacher-enrollment/', admin_teacher_enrollment_view, name='admin-teacher-enrollment'),
    path('admin/course-cuts/', admin_course_cuts_view, name='admin-course-cuts'),
    path('admin/course-cuts/create/', admin_course_cut_create_view, name='admin-course-cut-create'),
    path('admin/course-cuts/close/', admin_course_cut_close_view, name='admin-course-cut-close'),
    path('admin/course-cuts/students/', admin_course_cut_students_view, name='admin-course-cut-students'),
    path('admin/course-cuts/students/sync/', admin_course_cut_students_sync_view, name='admin-course-cut-students-sync'),
    path('admin/course-cuts/schedule/', admin_course_cut_schedule_view, name='admin-course-cut-schedule'),
    path('admin/course-cuts/schedule/save/', admin_course_cut_schedule_save_view, name='admin-course-cut-schedule-save'),
    path('admin/course-cuts/teams/sync/', admin_course_cut_teams_sync_view, name='admin-course-cut-teams-sync'),
    path('admin/enrolled-students/', admin_enrolled_students_view, name='admin-enrolled-students'),
    path('admin/grade-transfer/', admin_grade_transfer_view, name='admin-grade-transfer'),
    path('admin/grade-transfer/save/', admin_grade_transfer_save_view, name='admin-grade-transfer-save'),
    path('admin/attendance/', admin_attendance_view, name='admin-attendance'),
    path('admin/attendance/save/', admin_attendance_save_view, name='admin-attendance-save'),
    path('admin/carrera-status/', admin_carrera_status_view, name='admin-carrera-status'),
    path('admin/pensum/', admin_pensum_entry_view, name='admin-pensum-entry'),
    path('admin/pensum-status/', admin_pensum_status_view, name='admin-pensum-status'),
    path('admin/bulk-enrollment/template/', admin_bulk_enrollment_template_view, name='admin-bulk-enrollment-template'),
    path('admin/bulk-enrollment/', admin_bulk_enrollment_view, name='admin-bulk-enrollment'),
    path('admin/payment-info/', admin_payment_info_view, name='admin-payment-info'),
    path('admin/payment-operations/', admin_payment_operations_view, name='admin-payment-operations'),
    path('admin/payment-operations/links/', admin_payment_operations_links_view, name='admin-payment-operations-links'),
    path('admin/payment-operations/generate/', admin_payment_operations_generate_view, name='admin-payment-operations-generate'),
    path('admin/payments/', admin_registered_payments_view, name='admin-registered-payments'),
    path('admin/payments/reconcile/', admin_payments_reconcile_view, name='admin-payments-reconcile'),
    path('admin/payments/register/', admin_payment_register_view, name='admin-payment-register'),
    path('admin/payments/discount/', admin_payment_discount_view, name='admin-payment-discount'),
    path('admin/payments/receipt/', admin_payment_receipt_generate_view, name='admin-payment-receipt-generate'),
    path('admin/payment-cancel/', admin_payment_cancel_view, name='admin-payment-cancel'),
]
