from django.urls import path

from .views import (
    admin_academic_catalogs_view,
    admin_bulk_enrollment_template_view,
    admin_bulk_enrollment_view,
    admin_carrera_status_view,
    admin_course_cut_close_view,
    admin_course_cut_create_view,
    admin_course_cuts_view,
    admin_payment_cancel_view,
    admin_payment_info_view,
    admin_pensum_entry_view,
    admin_pensum_status_view,
    health_view,
    inscription_certificate_view,
    inscription_catalogs_view,
    inscription_generate_matricula_view,
    inscription_payment_link_view,
    login_view,
    microsoft365_create_user_view,
    microsoft365_student_license_view,
    student_lookup_view,
)


urlpatterns = [
    path('health/', health_view, name='auth-health'),
    path('login/', login_view, name='auth-login'),
    path('inscription/lookup/', student_lookup_view, name='student-lookup'),
    path('inscription/catalogs/', inscription_catalogs_view, name='inscription-catalogs'),
    path('inscription/matricula/', inscription_generate_matricula_view, name='inscription-matricula'),
    path('inscription/payment-link/', inscription_payment_link_view, name='inscription-payment-link'),
    path('inscription/certificate/', inscription_certificate_view, name='inscription-certificate'),
    path('microsoft365/users/', microsoft365_create_user_view, name='microsoft365-create-user'),
    path('microsoft365/licenses/student/', microsoft365_student_license_view, name='microsoft365-student-license'),
    path('admin/academic-catalogs/', admin_academic_catalogs_view, name='admin-academic-catalogs'),
    path('admin/course-cuts/', admin_course_cuts_view, name='admin-course-cuts'),
    path('admin/course-cuts/create/', admin_course_cut_create_view, name='admin-course-cut-create'),
    path('admin/course-cuts/close/', admin_course_cut_close_view, name='admin-course-cut-close'),
    path('admin/carrera-status/', admin_carrera_status_view, name='admin-carrera-status'),
    path('admin/pensum/', admin_pensum_entry_view, name='admin-pensum-entry'),
    path('admin/pensum-status/', admin_pensum_status_view, name='admin-pensum-status'),
    path('admin/bulk-enrollment/template/', admin_bulk_enrollment_template_view, name='admin-bulk-enrollment-template'),
    path('admin/bulk-enrollment/', admin_bulk_enrollment_view, name='admin-bulk-enrollment'),
    path('admin/payment-info/', admin_payment_info_view, name='admin-payment-info'),
    path('admin/payment-cancel/', admin_payment_cancel_view, name='admin-payment-cancel'),
]
