export const DASHBOARD_ROUTES = [
  {
    id: 'home',
    hash: '#dashboard',
    label: 'Dashboard',
    title: 'Dashboard general',
    description: 'Selecciona una opción para administrar procesos institucionales.',
  },
  {
    id: 'academic',
    hash: '#academic',
    aliases: ['#admin-academic'],
    label: 'Carreras y pensum',
    title: 'Carreras y pensum',
    description: 'Administra carreras, materias, estados y filtros académicos.',
  },
  {
    id: 'course-cuts',
    hash: '#course-cuts',
    aliases: ['#admin-course-cuts'],
    label: 'Cortes',
    title: 'Cortes de inscripción',
    description: 'Abre y cierra cortes para organizar matrículas, certificados y cargas Excel.',
  },
  {
    id: 'course-students',
    hash: '#course-students',
    aliases: ['#admin-course-students'],
    label: 'Estudiantes corte',
    title: 'Estudiantes de corte',
    description: 'Consulta estudiantes por corte y sincronízalos con educación continua.',
  },
  {
    id: 'enrolled-students',
    hash: '#enrolled-students',
    aliases: ['#admin-enrolled-students', '#matriculados'],
    label: 'Matriculados',
    title: 'Estudiantes matriculados',
    description: 'Consulta los estudiantes matriculados en educación continua por corte.',
  },
  {
    id: 'attendance',
    hash: '#attendance',
    aliases: ['#admin-attendance', '#asistencia'],
    label: 'Asistencia',
    title: 'Asistencia',
    description: 'Registra asistencia de estudiantes matriculados en educación continua por corte.',
  },
  {
    id: 'admin-schedule',
    hash: '#admin-schedule',
    aliases: ['#admin-horario', '#horario-admin', '#schedule-admin'],
    label: 'Horario',
    title: 'Horario',
    description: 'Crea horarios por corte y genera sesiones de clase.',
  },
  {
    id: 'admin-teams',
    hash: '#admin-teams',
    aliases: ['#teams-admin', '#matricula-teams', '#admin-teams-enrollment'],
    label: 'Teams',
    title: 'Matrícula por Teams',
    description: 'Matricula docentes y estudiantes en Teams usando el horario guardado.',
  },
  {
    id: 'grade-transfer',
    hash: '#grade-transfer',
    aliases: ['#admin-grade-transfer', '#pase-notas'],
    label: 'Pase de notas',
    title: 'Pase de notas',
    description: 'Registra una nota final y sincronízala en complemento e INTECBDD.',
  },
  {
    id: 'certificate-template',
    hash: '#certificate-template',
    aliases: ['#admin-certificados', '#plantilla-certificado', '#certificado'],
    label: 'Certificado',
    title: 'Certificado',
    description: 'Genera certificados por corte y administra la plantilla institucional.',
  },
  {
    id: 'payments',
    hash: '#payments',
    aliases: ['#admin-payments'],
    label: 'Pagos',
    title: 'Pagos',
    description: 'Consulta transacciones y ejecuta anulaciones desde un módulo independiente.',
  },
  {
    id: 'bulk-enrollment',
    hash: '#bulk-enrollment',
    aliases: ['#admin-bulk-enrollment'],
    label: 'Matrícula académica',
    title: 'Matrícula académica',
    description: 'Procesa estudiantes por Excel o selección, matricula materias y envía credenciales INTEC.',
  },
  {
    id: 'teacher-entry',
    hash: '#teacher-entry',
    aliases: ['#admin-teacher-entry'],
    label: 'Registro docente',
    title: 'Registro docente',
    description: 'Registra docentes y envía credenciales Microsoft 365 para profesores.',
  },
  {
    id: 'teacher-enrollment',
    hash: '#teacher-enrollment',
    aliases: ['#admin-teacher-enrollment'],
    label: 'Matrícula docente',
    title: 'Matrícula docente',
    description: 'Busca docentes ingresados por nombre o cédula y asígnalos a materias.',
  },
  {
    id: 'teacher-attendance',
    hash: '#teacher-attendance',
    aliases: ['#asistencia-docente'],
    label: 'Asistencia',
    title: 'Asistencia',
    description: 'Consulta el resumen de asistencia de los cursos asignados al docente.',
  },
  {
    id: 'teacher-grades',
    hash: '#teacher-grades',
    aliases: ['#calificaciones-docente'],
    label: 'Calificaciones',
    title: 'Calificaciones',
    description: 'Consulta el avance de calificaciones de los cursos asignados al docente.',
  },
  {
    id: 'teacher-schedule',
    hash: '#teacher-schedule',
    aliases: ['#horario-docente'],
    label: 'Horario',
    title: 'Horario docente',
    description: 'Carga horarios por corte para reflejarlos a estudiantes.',
  },
  {
    id: 'student-schedule',
    hash: '#student-schedule',
    aliases: ['#horario-estudiante', '#horario'],
    label: 'Horario',
    title: 'Horario',
    description: 'Consulta los horarios cargados por el docente para tus materias matriculadas.',
  },
  {
    id: 'student-grades',
    hash: '#student-grades',
    aliases: ['#calificaciones-estudiante', '#certificados-estudiante', '#certificado'],
    label: 'Calificaciones',
    title: 'Calificaciones',
    description: 'Consulta tus notas en modo lectura y gestiona el certificado de aprobación.',
  },
]

export function routeFromHash(hash) {
  const normalizedHash = hash || '#dashboard'
  const route = DASHBOARD_ROUTES.find(
    (item) => item.hash === normalizedHash || item.aliases?.includes(normalizedHash),
  )
  return route?.id || 'home'
}

export function routeById(routeId) {
  return DASHBOARD_ROUTES.find((item) => item.id === routeId) || DASHBOARD_ROUTES[0]
}
